### ISSUE TITLE
Calculate COP

### ISSUE THREAD

**Issue by tuimz** [marcoboers/home-assistant-quatt#103]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/quatt/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Since the CiC now provides us with a `heatpump_hp1_powerinput` how can I (after the integration is installed) use that sensor to calculate the COP.

The question for powersensor only comes with the first installation flow.

Perhaps it would be best to integrate a new sensor that automatically uses `heatpump_hp1_powerinput` to calculate the COP?

### Describe the solution you'd like

Calculate the COP independently of Quatt

### Describe alternatives you've considered

Creating a manually configured template sensor

### Additional context

.

**Comment by patrickvorgers** [comment]
With the integration you have two calculated COP's:

- **HP1 COP**
Calculation:
WaterDelta = (TemperatureWaterOut - TemperatureWaterIn)
HeatPower = WaterDelta * FlowRate * 1.137888
COP = HeatPower / ElectricalPower

The electrical power is an external powermeter

- **HP1 Quatt COP**
COP = PowerOutput / PowerInput

The PowerInput and PowerOutput is the power calculated by Quatt itself

Looking at you question it seems to me that the COP is already calculated based on the PowerInput. What are you missing?

**Comment by tuimz** [comment]
When installing the integration (and also described in the readme) there is a question step to insert a sensor for an external power meter.

There is no way to configure that power meter sensor after installing. I was wondering if that is even still needed since we indeed have the Quatt COP calculation OR we could use PowerInput sensor from the integration (as input for HP1 COP)

This could reduce the need for an external sensor. I am a little bit sceptical when it comes to putting in a "random" power measurement plug on such a high powered device. Then again I have no idea on what a Quatt actually uses since mine was placed just a couple of weeks ago ;)

**Comment by patrickvorgers** [comment]
The "HP1 COP" was introduced in one of the first versions of the integration when the Quatt did not yet provide PowerOutput and PowerInput. I think that the Quatt uses internally a similar formula to calculate the COP.

I agree that it would be usefull to be able to change the configuration after configuration. Some integrations provide that functionality. This would be a feature request.

**Comment by tuimz** [comment]
Thank you, I will see if I can change this an open a PR

**Comment by patrickvorgers** [comment]
I created a PR which implements this feature. I don't know when it will be merged. It seems that the maintainer is not that active anymore.
