### ISSUE TITLE
0.6.0b3 My CIC is discovered again after enabling beta channel

### ISSUE THREAD

**Issue by w-Oeps** [marcoboers/home-assistant-quatt#118]
## System Information

version | core-2024.9.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1425
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 19.2 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Mosquitto broker (6.4.1), Samba Backup (5.2.0), Samba share (12.3.2), rsync (1.7.0), Advanced SSH & Web Terminal (19.0.0), Log Viewer (0.17.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 3
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 27 September 2024 at 14:49
-- | --
current_recorder_run | 29 September 2024 at 11:39
estimated_db_size | 260.86 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/quatt/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

(The previous issue link gives a 404).
I changed my Test HA system to use the beta channel for Quatt HA integration .
This worked fine and got the configuration option to add the Power sensor. So far so good.
Then I did the same at my production HA system and the Intgration discovered a 'new' Quatt CIC.
Now I have two. The entities of the second have a suffix "2". For now I disabled the newly discovered CIC.
I do not hava any explanation as only a few hours was between the update of Test HA and Prod HA, No network changes for example.
Not a big issue as you can disable the new one. I some testing is need I can enable it otherwise I will delete it. More to let you know it might occur when the beta Quatt integration becomes the stable version.
Screenshots attached.
<img width="346" alt="Existing Sensor name" src="https://github.com/user-attachments/assets/0cc24441-926f-45af-8a9c-ca3a16034840">
<img width="773" alt="Quat CIC discovered twice" src="https://github.com/user-attachments/assets/9c1f5bba-4bb9-47a3-b14a-aa86eca40fbd">
<img width="338" alt="New Sensor name" src="https://github.com/user-attachments/assets/bcdc7bd8-79ee-4d34-ad27-394bb186ae0c">

### Reproduction steps

1. No reproduction done

### Debug logs

```text
No debug log available as the upgrade was done without debug logging enabled
```

**Comment by patrickvorgers** [comment]
The autodiscovery matches on the CIC-id.
Can you have a look at the following file: `config/.storage/core.config_entries` and search for the keyword `quatt`. It should find the configuration for the quatt. Because you now have two configurations please have a look at the `unique_id` for each entry and check whether they contain the CIC-id.

**Comment by w-Oeps** [comment]
Thanks for looking into this.
The entry if the 'original' CIC:
`{
        "created_at": "1970-01-01T00:00:00+00:00",
        "data": {
          "ip_address": "192.168.178.196"
        },
        "disabled_by": null,
        "domain": "quatt",
        "entry_id": "89debdcfe2687e62c516363f82fe66b7",
        "minor_version": 1,
        "modified_at": "2024-09-30T04:52:03.025291+00:00",
        "options": {
          "scan_interval": 10,
          "power_sensor": "sensor.hp_phase_1_2_total_input_power"
        },
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "title": "CIC-31bd3f10-3106-525c-xxxx-yyyyyyyyyyyy",
        "unique_id": "CIC-31bd3f10-3106-525c-xxxx-yyyyyyyyyyyy",
        "version": 2
      }`

The newly discovered CIC, now disabled:
`{
        "created_at": "2024-09-29T19:37:11.645377+00:00",
        "data": {
          "ip_address": "192.168.178.196"
        },
        "disabled_by": "user",
        "domain": "quatt",
        "entry_id": "01J8ZMJX6XNJ549HGZVC6Y5DCH",
        "minor_version": 1,
        "modified_at": "2024-09-29T19:37:11.645388+00:00",
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "dhcp",
        "title": "cic-quatt",
        "unique_id": "CIC-quatt",
        "version": 2
      }`

The only differences between my Test-HA (which did not a second discovery) and Prod-HA is that Test-HA is running on Proxmox on a x86 system and Prod-HA is an RPI4, both running core.
It seems the original discovery was on unique-id and the second on hostname. Don't know how unique-id would be advertised on the network.

**Comment by patrickvorgers** [comment]
It seems like the newly discovered CIC has a quite different name "CIC-quatt". Normally it is in the form of "CIC-31bd3f10-3106-525c-xxxx-yyyyyyyyyyyy". Did you give the CIC a name or is that the standard name from Quatt?

Can you have a look at the json page: `http://<quatt ip>:8080` and then system.hostName?

**Comment by w-Oeps** [comment]
From the CIC: system.hostName	CIC-31bd3f10-3106-525c-xxxx-yyyyyyyyyyyy
and you made me think :-)
I gave the CIC a name in my Fritzbox: CIC-Quatt. My Pi-hole is DNS with the Fritzbox as upstream. This means that the Fritzbox is in charge of delivering the hostname.
I must have done this _after_ I installed the Quatt integration as I installed it right after the Quatt engineers left the house.
Now when switching to beta discovery finds the defined hostname. 
More or less a edge case. Maybe 'solve' it in documentation.

**Comment by patrickvorgers** [comment]
Seems also like an edge case to me.
It would have worked if you would have installed it before the Quatt integration. Now it is recognized as a new CIC because it has a different name which is from an implementation perspective correct.

I think it is best to close this issue.

@marcoboers, can you close this one?

**Comment by w-Oeps** [comment]
Closed as edge case
