### ISSUE TITLE
Issues with defrost binary sensor

### ISSUE THREAD

**Issue by jeroen85** [marcoboers/home-assistant-quatt#130]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/quatt/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I experience a lot of Defrost cases with my HP1 while it is not defrosting at all. It happens during start of the HP.

![bnpG0hOhZCTf9QlpiHMuM6PH](https://github.com/user-attachments/assets/3d431672-86e8-40d8-b388-63f0e55d75a7)

in my case it is caused by a small temperature difference of the water inlet and outlet sensor when the HP is not in use. This results in the power measurement becoming negative, exceeding -100W and triggering the defrost binary sensor.
![gQ3RuQAqn5hKC7khNQJZug2n](https://github.com/user-attachments/assets/5bd6c296-415d-42a6-b682-5bed8c47da6a)

Maybe some additional parameters should be checked to determine defrost situations?

### Reproduction steps

N/A

### Debug logs

```text
N/A
```

**Comment by jeroen85** [comment]
As the heat power decreases up to -6000W during defrost I would suggest to change the threshold to something like -2000W instead of -100W

**Comment by patrickvorgers** [comment]
What I see in the code is that it uses the `power` and `powerinput` from the Quatt and not the waterdelta.
Can you create a graph of a longer period of the `power` and `powerinput` of HP1?

**Comment by patrickvorgers** [comment]
Looking at my own Quatt (don't have a duo), it seems like that changing the `heatpower` check to -2500 could do the trick.

![image](https://github.com/user-attachments/assets/0f6cb714-97e8-4490-8ed2-f9fdaf149703)

Could you change in the file `coordinator.py` (custom_components/quatt) the `computedDefrost` function?
Especially the return statement which checks the ranges of the input and output power.
After the change you have to restart Home Assistant to activate the change.
Please check whether that fixes the issue for you.

```
    def computedDefrost(self, parent_key: str | None = None):
        """Compute Quatt Defrost State."""
        if parent_key is None:
            return None

        powerInput = self.getValue(parent_key + ".powerInput")
        powerOutput = self.getValue(parent_key + ".power")

        LOGGER.debug("%s.computedDefrost.powerInput %s", parent_key, powerInput)
        LOGGER.debug("%s.computedDefrost.powerOutput %s", parent_key, powerOutput)

        if powerInput is None or powerOutput is None:
            return None

        powerOutput = float(powerOutput)
        powerInput = float(powerInput)

        return powerOutput < -2500 and powerInput > 100
```

**Comment by jeroen85** [comment]
> What I see in the code is that it uses the `power` and `powerinput` from the Quatt and not the waterdelta. Can you create a graph of a longer period of the `power` and `powerinput` of HP1?

The `power` is a calculated value within the CiC. It is the` flow * heat capacity of water * T_waterdelta`. As the ` T_waterdelta` becomes slightly negative (-0,1 degC), the resulting power measurement also get's negative. This exceeds the threshold of -100W and triggers the defrost binary.

I will change the `coordinator.py` file, thanks for the suggestion!

**Comment by patrickvorgers** [comment]
> > What I see in the code is that it uses the `power` and `powerinput` from the Quatt and not the waterdelta. Can you create a graph of a longer period of the `power` and `powerinput` of HP1?
> 
> The `power` is a calculated value within the CiC. It is the` flow * heat capacity of water * T_waterdelta`. As the ` T_waterdelta` becomes slightly negative (-0,1 degC), the resulting power measurement also get's negative. This exceeds the threshold of -100W and triggers the defrost binary.
> 
> I will change the `coordinator.py` file, thanks for the suggestion!

You are right that the CIC uses a similar formula as the Quatt integration when an external powermeter is used to calculate the produced heat `computedWaterDelta * flowRate * 1.137888`.

Great that you are going to test out the change. Please report back whether it fixes the issue. I will also apply the change myself and check the effects on a single Quatt. After some testing I will create a pull request (PR) for the change.

**Comment by jeroen85** [comment]
It worked as expected. Binary sensor indicated defrost when power was below -2500W.
No defrost for small power drops (for example the -233W around 12:00)

![Screenshot 2024-11-04 200315](https://github.com/user-attachments/assets/cbd12bb8-94aa-4254-9fc8-1573158893f2)

**Comment by patrickvorgers** [comment]
@jeroen85, I created a PR with the fix. Hopefully it will be merged soon.

**Comment by jeroen85** [comment]
I will, unfortunately no defrosts these days
