### ISSUE TITLE
Power sensor for HP2 or total power sensor

### ISSUE THREAD

**Issue by Fidelity88** [marcoboers/home-assistant-quatt#46]
I’m missing the power sensor for HP2 (sensor.heatpump_hp1_powerinput).

Without this, you can never know the full power usage of your HP setup assuming you have 2 devices.

For example, right now Home Assistant reports 0 watt usage. But the Quatt app reports 310 watt usage. Probably because HP2 is running and HP1 is simply idle.

Or am I missing something?

**Comment by marcoboers** [comment]
You are right. Will try to pick this up in the weekend

**Comment by Fidelity88** [comment]
Please let me know when you have an update on this @marcoboers

**Comment by marcoboers** [comment]
@Fidelity88 I have added the power and COP sensors and

**Comment by Fidelity88** [comment]
Amazing, I'd love to try! Any idea how fast the update will be picked up by HACS? Or any idea how I can force the update now?

![Screenshot 2023-11-15 at 10 38 51](https://github.com/marcoboers/home-assistant-quatt/assets/2750761/84ed7ed4-5e94-4f7c-b462-192051262bc1)

**Comment by Fidelity88** [comment]
Works perfectly, one coffee coming your way!
