### ISSUE TITLE
Adjust computedWaterDelta & computedQuattCop for a Quatt DuoBlock

### ISSUE THREAD

**Issue by pegasus75** [marcoboers/home-assistant-quatt#53]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/quatt/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The current calculations seem to be wrong for a duoblock

### Describe the solution you'd like

Below the updates for the duo block:

    def computedWaterDelta(self):
        """Compute waterDelta."""
        temperatureWaterOut = self.getValue("hp2.temperatureWaterOut")
        temperatureWaterIn = self.getValue("hp1.temperatureWaterIn")
        LOGGER.debug("computedWaterDelta.temperatureWaterOut %s", temperatureWaterOut)
        LOGGER.debug("computedWaterDelta.temperatureWaterIn %s", temperatureWaterIn)
        if temperatureWaterOut is None or temperatureWaterIn is None:
            return None
        if temperatureWaterOut < temperatureWaterIn:
            return None
        return round(temperatureWaterOut - temperatureWaterIn, 2)

    def computedQuattCop(self):
        """Compute Quatt COP."""
        powerInput = self.getValue("hp1.powerInput") + self.getValue("hp2.powerInput")
        powerOutput = self.getValue("hp1.power") + self.getValue("hp2.power")
        LOGGER.debug("computedQuattCop.powerInput %s", powerInput)
        LOGGER.debug("computedQuattCop.powerOutput %s", powerOutput)
        if powerInput is None or powerOutput is None:
            return None
        if powerInput == 0:
            return None
        return round(powerOutput / float(powerInput), 2)

### Describe alternatives you've considered

Accepting the error

### Additional context

-

**Comment by marcoboers** [comment]
The waterDelta is actually under HP1 and not implemented for HP2. I will add a waterDelta sensor under HP2 as well as a generic one for the total waterdelta for DuoBlock. 
Since I don't have a DuoBlock, would you be willing to test this? I can make a beta release that you can install through HACS.

**Comment by pegasus75** [comment]
Hoi Marco,
Ik test het graag hoor en werk graag mee aan dit project.
Groeten,
Pieter

**Comment by marcoboers** [comment]
@pegasus75 ik heb een beta release gemaakt 0.4.0b1. Onder HACS -> Quatt -> Redownload kun je die zichtbaar maken en selecteren https://hacs.xyz/docs/faq/beta/.

Je zal de nieuwe sensors nog zelf even moeten enablen. Ik hoor graag of alles naar behoren werkt.

**Comment by pegasus75** [comment]
Overigens heb ik zelf nog 2 andere sensoren gedefinieerd, misschien kan je deze ook nog toevoegen?

template:
  - sensor:
      - name: "Quatt Total Power Input" 
        unique_id: "quatt_total_power_input" 
        unit_of_measurement: "W"  # Assuming the unit is Watts. Change this if needed.
        state: >
          {{ (states('sensor.heatpump_hp1_powerinput') | float | round(0) ) +
             (states('sensor.heatpump_hp2_powerinput') | float | round(0) ) 
          }}
        attributes:
          friendly_name: "quatt Total Power Input"
  - sensor:
      - name: "Quatt Total Power Output"
        unique_id: "quatt_total_power_output"
        unit_of_measurement: "W"  # Assuming the unit is Watts. Change this if needed.
        state: >
          {{ (states('sensor.heatpump_hp1_power') | float | round(0) ) +
             (states('sensor.heatpump_hp2_power') | float | round(0) )
          }}
        attributes:
          friendly_name: "quatt Total Power"
########### Totaal energie verbruik
  - sensor:
      - name: "energy_consumption_total"
        unique_id: "energy_consumption_total"
        unit_of_measurement: "kWh"
        state: >
          {{ ((states('sensor.energy_consumption_tarif_1') | float(default=0)) +
           (states('sensor.energy_consumption_tarif_2') | float(default=0))) }}
        attributes:
          friendly_name: "energy_consumption_total"

**Comment by marcoboers** [comment]
I added those 2 sensors to the new beta release 0.4.0b2
