### ISSUE TITLE
Make the update_interval configurable

### ISSUE THREAD

**Issue by pegasus75** [marcoboers/home-assistant-quatt#54]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/quatt/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The current update_interval is static and is 10. This causes frequent data pulls and potential more data points that someone might need/want

### Describe the solution you'd like

I would like this variable to be configurable in the Integration

### Describe alternatives you've considered

Hardcoded change in coordinator.py

### Additional context

-

**Comment by marcoboers** [comment]
To be honest, I'm not sure if this is easy to do. There used to be a scan_interval but that was dropped by HA quite some time ago. Please let me know if you know of any integration that allows modifying the interval. I might be able to use it as inspiration.

**Comment by WebSpider** [comment]
The route I've seen a few integrations take to support this, is disable updating automatically, and add supporting update via a service call. Then the end-user gets to implement an automation to decide when to update.

**Comment by wouzzie** [comment]
Hi! Just stumbled upon this, but in my HA I use the Plugwise integration to control my thermostat. That integration (in the beta channel) supports setting the update interval manually from the configuration options. Might be a source of inspiration! https://github.com/plugwise/plugwise-beta

**Comment by patrickvorgers** [comment]
@marcoboers 

Looking at the code you are already using "update_interval" in the Coordinator. When I change the timedelta into 20 seconds the data is refreshed every 20 seconds. Am I missing something?

```
        super().__init__(
            hass=hass,
            logger=LOGGER,
            name=DOMAIN,
            update_interval=timedelta(seconds=20),
        )
```

**Comment by marcoboers** [comment]
I tagged a beta release! 
Make sure to go to settings -> devices -> HACS -> Quatt and turn on "Pre-release" toggle to be able to download the beta.
https://github.com/marcoboers/home-assistant-quatt/releases/tag/0.6.0b1

**Comment by marcoboers** [comment]
This has just been released.
https://github.com/marcoboers/home-assistant-quatt/releases/tag/0.6.0
