### ISSUE TITLE
Add a binary sensor to determine if a defrost is happening.

### ISSUE THREAD

**Issue by synga-nl** [marcoboers/home-assistant-quatt#55]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/quatt/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

/

### Describe the solution you'd like

A new binary sensor that determines if the quatt is currently in defrost mode. The easiest way is to check if the current heat power is less than zero (or use an offset of for example -100 watt)

### Describe alternatives you've considered

Create the sensor myself, but I think more users want to have a clear overview of defrosts.

### Additional context

/

**Comment by marcoboers** [comment]
I added defrost sensor for HP1 on basic conditions which seem to work quite well. 
Will look into adding it for HP2 as well somewhere next week.

![Screenshot_2023-12-03-15-57-58-01_c3a231c25ed346e59462e84656a70e50](https://github.com/marcoboers/home-assistant-quatt/assets/3316595/a7bd1037-f496-4aa6-9710-4657e147755d)
