### ISSUE TITLE
Question: why calculated heatPower sensor

### ISSUE THREAD

**Issue by Verguldebarman** [marcoboers/home-assistant-quatt#66]
Why does the integration have a heatPower sensor, while the standard Quatt sensor does the same?

**Comment by marcoboers** [comment]
The heatPower sensor was introduced by this integration for calculating the COP before the Quatt API exposed power and powerInput. Currently I would suggest to use the power and powerInput provided by Quatt and the Quatt COP sensor that uses the Quatt powers for its calculations.

**Comment by Verguldebarman** [comment]
Thx Marco!!

**Comment by Verguldebarman** [comment]
Thx Marco!!
